# Permalinks
permalink:           pretty

# Setup
title:               Sanjog 
tagline:             'Admin's Backyard'
description:         'Here at my Backyard I'll be updating everything which I feel like needs to be shared :) Find me on twitter <a href="https://twitter.com/sigdelsanjog" target="_blank">@sigdelsanjog</a>.'
url:                 ''
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sanjog Sigdel
  url:               https://twitter.com/sigdelsanjog
  email:             admin@techjhola.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
